### ISSUE TITLE
Protest to bring back the spamming Mee6 messages in general [DENIED]

### ISSUE THREAD

**Issue by brennan-macaig** [FRCDiscord/RoBot#2]
I just want them back. I already miss them. They've been gone for less than 10 minutes. Please just bring my baby back home.

**Comment by brennan-macaig** [comment]
Forgot to tag a particular commit: f3109a1

**Comment by Samcfuchs** [comment]
Damn that's cold

**Comment by astronautlevel2** [comment]
Despite the claims that this wouldn't be fixed, Mee6 messages have been allowed in #general again

**Comment by asianboiFRC** [comment]
However, they have been set to delete after a period of time @astronautlevel2 @brennan-macaig @Samcfuchs

**Comment by brennan-macaig** [comment]
So I won

**Comment by andrewda** [comment]
GG @brennan-macaig

**Comment by asianboiFRC** [comment]
@brennan-macaig no you didn't :P I'm going to fix it to auto delete (after a period of time) in a bit lol

**Comment by Samcfuchs** [comment]
Grats dude.
