### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by andrewda** [FRCDiscord/RoBot#3]
I saw that we now have a Travis-CI repository. Let's add some Node.js tests to stop the build from failing.

We should probably start with a simple ESLint, then move on to actual build tests after that (if we really want that - build tests for something like this seems a bit unnecessary, but they would be pretty fast).

**Comment by asianboiFRC** [comment]
soon lol after I rewrite it :P

**Comment by asianboiFRC** [comment]
Travis prevents me from pulling bad code, and it's for the new API repo as well

**Comment by asianboiFRC** [comment]
I'm spending a bit of time doing it now lol

**Comment by andrewda** [comment]
Should probably write an actual tests file and/or use a linter. Just running the bot just makes Travis-CI timeout (which doesn't throw an error for some reason).

**Comment by mikexcao** [comment]
I'll write some at a later date - I don't really know much about this stuff

**Comment by atf1999** [comment]
Ik im ghosting an old issue but TDD would not be bad
