### ISSUE TITLE
Specify version numbers/actually maintain package.json

### ISSUE THREAD

**Issue by atf1999** [FRCDiscord/RoBot#5]
Its sort of lazy to do * for the version number of the packages in your package.json.  Also, it might be good to keep package.json up to date, the urban package was not in it, and yet it was being used in the project (I fixed this, but this is a heads up as so it doesn't happen again)

**Comment by mcao** [comment]
This issue will be resolved in the next version of RoBot - it will hopefully be pushed to master by tonight.
