### ISSUE TITLE
Regenerate your bot key, removing the config file does not delete it from the history

### ISSUE THREAD

**Issue by nitros12** [FRCDiscord/RoBot#6]
448446dc91c04d91cd61aecf1d3276a2584af55f <- this means nothing, it is still possible to login to the bot with the removed key.

https://hastebin.com/uxibaroyaq.makefile

**Comment by atf1999** [comment]
Thank you for bringing this to our attention

**Comment by asianboiFRC** [comment]
I have regenerated the token 👍
